---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: code-server
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: codercom/code-server
      pullPolicy: Always
      # renovate: datasource=docker depName=codercom/code-server
      tag: 3.9.0
    strategy:
      type: Recreate
    env:
      TZ: ${TIMEZONE}
      PASSWORD: ${CODESERVER_PASSWORD}
      START_DIR: /config
    service:
      main:
        ports:
          http:
            port: 8080
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        cpu: 500m
        memory: 200Mi
    securityContext:                                                                                                                                                                                                                     │
      runAsUser: 0
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          traefik.ingress.kubernetes.io/router.tls: "true"
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "${SECRET_CLOUDFLARE_TUNNEL_ID}.cfargotunnel.com"
        hosts:
          - host: code.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: 8080
    persistence:
      config:
        enabled: true
        type: emptyDir
        accessMode: ReadWriteOnce
        size: 5Gi
        mountPath: /config
# docker run --entrypoint /bin/sleep docker.io/fluxcd/flux-cli:v0.37.0 inf
