---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: code-server
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/linuxserver/code-server
      pullPolicy: Always
      # renovate: datasource=docker depName=ghcr.io/linuxserver/code-server
      tag: 4.91.1
    strategy:
      type: Recreate
    env:
      TZ: ${TIMEZONE}
      PUID: 911
      PGID: 911
      PROXY_DOMAIN: code.${SECRET_DOMAIN_K8S}
      PASSWORD: ${CODESERVER_PASSWORD}
      DOCKER_MODS: linuxserver/mods:universal-git|linuxserver/mods:code-server-shellcheck|linuxserver/mods:code-server-terraform|linuxserver/mods:code-server-extension-arguments
      DEFAULT_WORKSPACE: /config/workspace
      VSCODE_EXTENSION_IDS: oderwat.indent-rainbow|ms-kubernetes-tools.vscode-kubernetes-tools|redhat.vscode-yaml|eamodio.gitlens|exiasr.hadolint|will-stone.in-any-case|britesnow.vscode-toggle-quotes|github.vscode-pull-request-github
      EXTENSIONS_GALLERY:
        '{"serviceUrl": "https://marketplace.visualstudio.com/_apis/public/gallery","cacheUrl":
        "https://vscode.blob.core.windows.net/gallery/index","itemUrl": "https://marketplace.visualstudio.com/items","controlUrl":
        "","recommendationsUrl": ""}'
      # DOCKER_MODS: "linuxserver/mods:code-server-docker|linuxserver/mods:code-server-python3|linuxserver/mods:code-server-shellcheck|linuxserver/mods:code-server-terraform|linuxserver/mods:universal-git|linuxserver/mods:universal-tshoot|linuxserver/mods:universal-package-install"
      # INSTALL_PACKAGES: "rsync|git|nginx"
      # INSTALL_PIP_PACKAGES: "apprise"
    service:
      main:
        ports:
          http:
            port: 8443
    # resources:
    #   requests:
    #     cpu: 10m
    #     memory: 50Mi
    #   limits:
    #     cpu: 500m
    #     memory: 200Mi
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          traefik.ingress.kubernetes.io/router.tls: "true"
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: ipv4.${SECRET_DOMAIN_K8S}
        hosts:
          - host: code.${SECRET_DOMAIN_K8S}
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: 8443
    persistence:
      config:
        enabled: true
        type: pvc
        accessMode: ReadWriteOnce
        size: 5Gi
        mountPath: /config
      # ssh-keys:
      #   enabled: true
      #   type: secret
      #   name: ssh-keys
      #   mountPath: /config/.ssh
      # gitconfig:
      #   enabled: true
      #   name: gitconfig
      #   type: configMap
      #   items:
      #     - key: .gitconfig
      #       path: .gitconfig
      #   subPath:
      #     - path: .gitconfig
      #       mountPath: /config/.gitconfig
# docker run --entrypoint /bin/sleep docker.io/fluxcd/flux-cli:v0.37.0 inf
