---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app guacamole
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: docker.io/maxwaldorf/guacamole
      tag: 1.5.0
    env:
      TZ: "${TIMEZONE}"
      GUACD_HOSTNAME: "guac.${SECRET_DOMAIN}/"
    controller:
      replicas: 1
      strategy: RollingUpdate
      annotations:
        reloader.stakater.com/auto: "true"
    service:
      main:
        type: LoadBalancer
        ports:
          http:
            port: &port 8080
    ingress:
      main:
        enabled: true
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "remote-desktop"
          hajimari.io/group: "utils"
          kubernetes.io/ingress.class: nginx
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "${SECRET_CLOUDFLARE_TUNNEL_ID}.cfargotunnel.com"
          nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
          # nginx.ingress.kubernetes.io/proxy-body-size: 1024m
          # nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
          # nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
          # nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
        hosts:
          - host: &host "guac.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: *host
    # probes:
    #   liveness: &probes
    #     enabled: true
    #     custom: true
    #     spec:
    #       httpGet:
    #         path: /
    #         port: *port
    #       initialDelaySeconds: 10
    #       periodSeconds: 10
    #       timeoutSeconds: 1
    #       failureThreshold: 3
    #   readiness: *probes
    #   startup:
    #     enabled: false
    persistence:
      config:
        enabled: true
        type: pvc
        accessMode: ReadWriteOnce
        size: 5Gi
#      usermapping-cm:
#        enabled: true
#        type: configMap
#        name: usermapping-cm
#        subPath: user-mapping.xml
#        mountPath: /config/guacamole/user-mapping.xml
#        defaultMode: 0777
#      guacprop-cm:
#        enabled: true
#        type: configMap
#        name: guacprop-cm
#        subPath: guacamole.properties
#        mountPath: /config/guacamole/guacamole.properties
#        defaultMode: 0777
#    resources:
#      requests:
#        cpu: 10m
#        memory: 50Mi
#      limits:
#        memory: 500Mi
