---
kubernetes:
  children:
    master:
      hosts:
        tpi-node1:
          ansible_host: tpi-node1
        tpi-node2:
          ansible_host: tpi-node2
        tpi-node3:
          ansible_host: tpi-node3
