apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:yf+p7asnX4qJLpcCSZAxXeU0cL8kj9/U2E96ne/7cIBIUqLyafQddg==,iv:qEO/ImCWIU4Czz8bm2ZnzOvn6WhtpAyfzfdrzdA84bM=,tag:b9sGu2N1lpCtiONJ/Oh8RQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y0kzuf0tn94a74whazwae4r9qal4snuqfuhl5jacscrpr7up5gts74fe5w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkRSt6MTQxYkdGeFQ3Y1U3
            bldCdFVWQS83bnlVZ09xUTZzV1NzWE9YNjJBCjVtWStJam8wUVQ2TWZMWW9LUHhk
            UEJPTEt6NGtUVWRoL3Y0MllZd2RvZ1UKLS0tIDFzT1pPMzg4RkV6Z0x3R29mdW01
            dUJuaWdCS3RHcjF6M09tSldHanNHUFkKrEWwdI0ij8Xs5W7ma+dlFAVYfBWvvrXH
            /ShMRJnqZQWwZp2au+03cTARI11GCOYgyATSCmBu+D521fK/M02Prw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-13T21:14:11Z"
    mac: ENC[AES256_GCM,data:N0vaGZtfwyoMHVYG7yKWP7gIOrC4WbMq+jRHLgWqeEaKIys2g1OUsfzzGHDHbab31Atd+0Kq8apdVlFy3YH601cmWllZTh8HFjWlj8C+xvDTv+oLgyJx7nH3qqeo7UughxbIlFbHDd46Uhke2phRtBuF7WYN2AUVl/aT9cTLWmw=,iv:r02wmVtgvggCFbP2RsJunCFpWt2lXUnI9HhadvpBi7s=,tag:Vc14bjCfkf/pcGIqj7KgyA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
