---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 15m
  timeout: 10m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 61.7.1
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  test:
    enable: false  # Enable helm test
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    timeout: 10m
    cleanupOnFail: true
    recreate: true
  values:
    fullnameOverride: prometheus
    prometheus-node-exporter:
      fullnameOverride: node-exporter
      prometheus:
        monitor:
          enabled: true
          relabelings:
            - action: replace
              regex: (.*)
              replacement: $1
              sourceLabels:
                - __meta_kubernetes_pod_node_name
              targetLabel: kubernetes_node
    prometheus:
      enabled: true
      persistentVolume:
        enabled: true
        size: 10Gi
      prometheusSpec:
        replicas: 1
        externalLabels:
          cluster: turingpi
        retention: 12h
        retentionSize: 10GB
        podAntiAffinity: hard
        replicaExternalLabelName: __replica__
        scrapeInterval: 1m
        ruleSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false
        probeSelectorNilUsesHelmValues: false
        enableAdminAPI: true
        walCompression: true
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: nfs-csi
              resources:
                requests:
                  storage: 10Gi
        resources:
          requests:
            cpu: 10m
            memory: 1000Mi
          limits:
            memory: 8000Mi
