---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-prometheus-app
  namespace: flux-system
spec:
  path: ./kubernetes/apps/monitoring/prometheus/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-flux
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: kube-prometheus-stack
      namespace: monitoring
  interval: 30m
  retryInterval: 1m
  timeout: 5m
