apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:iY1yR9o8MjEUzu0axAHuRaS77Rc9jKn4FXd8+Bs87pxArff+Qs566f7lbxnaql12jE+TQF7b/3H+2TS1,iv:BJodANtZGM25hcB6XBnoxjQe8FSlqaB/cuzED4sL+PM=,tag:8OaiBAsSE8SzhcVwMp1RCw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y0kzuf0tn94a74whazwae4r9qal4snuqfuhl5jacscrpr7up5gts74fe5w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbmo2V0xsRkFMMi9mbFR3
            TE10d1RLV2hwZHI0QytnRzExUEtrZVlTamlJCkNraFh2cWtVanRCUWt5cE5zdFN5
            a0pUUDdoL2NVbDVjMHNBaEI4ZlJ6bUUKLS0tIHR1YXh0dVF5bjQxSXFxU085OWM5
            Q2lJaUhxeDJZSVlCM0tkaDBtbU1xamMKOzjdenrGRTunKxNqBbEXrTssAsBW+S7v
            lfSofByjLW3MIROVeoPhoNdihAdQFsAHr5bL+X2ZwNeSwf+d8Cboag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-13T21:14:12Z"
    mac: ENC[AES256_GCM,data:q3pc6T8H/nl3tRUyfRhmY1RAfRtMk3f0OKYNaUF8XTIwEGXHyDB4aQ8W9DgQthML4SbUdLrb1iaT1GGch14gAx4B5TzmIDpHVEuaoJytfRyc1770ACuE19qK5gMymRgXOd0fEeqyBJLwmYUVFaWCqjZJJNYW7coLtHcmB8Rf7Cg=,iv:VQeNVfwVg8yNGK9aRYmR89YoKPVBvaHdGLpgcCpVbQ0=,tag:cbc73FcQLcOqttZk/tPs9A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
