---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Europe/Zurich"
  KUBE_VIP_ADDR: "192.168.8.111"
  METALLB_LB_RANGE: "192.168.8.180-192.168.8.199"
  METALLB_K8S_GATEWAY_ADDR: "192.168.8.185"
  METALLB_INGRESS_ADDR: "192.168.8.188"
