apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:wL94SLyVxUsPPbfP4R4=,iv:o0Q+BupORMS0AWJ9pdiovQJfH6+89H7++TDsH/jaT30=,tag:mp3Cp8ypFkhWYfnAUU67nw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:vutka5UTm/FEOxIll/lIxlsLAXI=,iv:Q9zCpRyAsehrXX4heXyer+7ZPExZyt5DvxeQf9o6w0Y=,tag:C6mtU/dw9m1BXWYJ5TLaTQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:coevYxQxNlcxzhLdSeZtwLn0h7SdQEkkh5Be/APAFREY7bSD,iv:ubX0hou9utixNOrPtv7qtVlEFe1DvbwcSlpI/h75Ed4=,tag:ZA4xwZkUdVUTp/FVtV2Emw==,type:str]
    CODESERVER_PASSWORD: ENC[AES256_GCM,data:w2W8D9hjyI4Iwa5E,iv:EDmBAHj1KYAe/aamkxRTws65ghm3Sl5PzhZMDPEhd+I=,tag:eZQF5RZAEBnV3AogTHYcBQ==,type:str]
    TIMEZONE: ENC[AES256_GCM,data:UMbXQjXweF8hpsPqSw==,iv:oi36XgM/NaA1RRqCTqe8XLi/wmScOgg5LXPBgbNgf60=,tag:NsRKE3IxlEsM5p1sd02mCQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y0kzuf0tn94a74whazwae4r9qal4snuqfuhl5jacscrpr7up5gts74fe5w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjTmJSbVFDRFVlYXgrcGtj
            SVd2R1loZHFFNU0zQ3p2enhQMGFJUHBYNDEwCmh3Q042VjEwaXJPQnh0OFBkN2k5
            a28ray83WlpFVW9EbnVrUS9jQTVUNDAKLS0tIDhvMG1zY2RDbDBKcWg3UEJqWmNo
            d2VzZ0NPVndlYUl4dytJVVQwSzNXb3MKZXyaD5AetUFdHxxpStEdnUXynj2ZqZwU
            zsqiP62R1ZHXZDcHHkz5JKmxz2RFBJePthm/ULP6kwoHNF2NfrdSOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-24T21:09:13Z"
    mac: ENC[AES256_GCM,data:t74kdF4MyFeF/FsuOl2u28JfyOc8NXKq2vBFbO0WzvRv99QtwEdj31eYCJiilwrdRepgvRDF1hiHI65AIsonXmdVnC7u1exuM1+xRT90h3fWc45SWa/Q6/R/9fQqYJWP4UAjezJW8Md+7RKwRqxv6+kw2AC4YApLFOa+OiXwejQ=,iv:k0Ih5jOaZY5qQ9bpI9G1IzIsPFnAB8rxZjSnmRiKuPo=,tag:hav5xzMOXz5sQxMGzFo9rQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
