apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:wL94SLyVxUsPPbfP4R4=,iv:o0Q+BupORMS0AWJ9pdiovQJfH6+89H7++TDsH/jaT30=,tag:mp3Cp8ypFkhWYfnAUU67nw==,type:str]
    SECRET_DOMAIN_ME: ENC[AES256_GCM,data:iYpMLqXZAdJjzWpWUPFy,iv:I0d6izLvoSKcL+WNqv56Bhl3vFh61Pj2r9qmY/n6yT4=,tag:2o5Pm54GcpID11f4qD56Wg==,type:str]
    SECRET_DOMAIN_INTERNAL: ENC[AES256_GCM,data:vtYjKYBHgXdKgtfsC7chwppQNA==,iv:udYi4dWW9TBsxK15xy9+S+CvU4pE0TRBv4ciXykMso8=,tag:KnROzDiAC4lRzo3Qvsn+ZQ==,type:str]
    SECRET_DOMAIN_CH: ENC[AES256_GCM,data:dLb90+YucZ7k9E8XKFUbAPc=,iv:si5MCWYj4HQTxaXP6aLmHQUeNapz/KU8ZGPq/ARkeqk=,tag:sJz5rylNqxOii2AyOR8pMg==,type:str]
    SECRET_DOMAIN_LAB: ENC[AES256_GCM,data:A4pmX7PCQa5gzGzgLE8e,iv:tgM7oTKz/J5zTBa0ElXcD/j1Vjy0cMTxQY1MaeUwdc4=,tag:c5fW4z3UXX6onLw8UYrVbA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:vutka5UTm/FEOxIll/lIxlsLAXI=,iv:Q9zCpRyAsehrXX4heXyer+7ZPExZyt5DvxeQf9o6w0Y=,tag:C6mtU/dw9m1BXWYJ5TLaTQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:coevYxQxNlcxzhLdSeZtwLn0h7SdQEkkh5Be/APAFREY7bSD,iv:ubX0hou9utixNOrPtv7qtVlEFe1DvbwcSlpI/h75Ed4=,tag:ZA4xwZkUdVUTp/FVtV2Emw==,type:str]
    CODESERVER_PASSWORD: ENC[AES256_GCM,data:w2W8D9hjyI4Iwa5E,iv:EDmBAHj1KYAe/aamkxRTws65ghm3Sl5PzhZMDPEhd+I=,tag:eZQF5RZAEBnV3AogTHYcBQ==,type:str]
    TIMEZONE: ENC[AES256_GCM,data:UMbXQjXweF8hpsPqSw==,iv:oi36XgM/NaA1RRqCTqe8XLi/wmScOgg5LXPBgbNgf60=,tag:NsRKE3IxlEsM5p1sd02mCQ==,type:str]
    SECRET_UPTIMEROBOT_APIKEY: ENC[AES256_GCM,data:BSNnJpJaiA77V0obPB3n0DeF4howo3vjdfHhsaM9UI4=,iv:lgZnAK2v99HdQHo7tZcUnYRdvazfkyXuKTGd8L+YKNo=,tag:8Nn1TkG4E2IaPO20LoJnAw==,type:str]
    SECRET_UPTIMEROBOTCONTACTS: ENC[AES256_GCM,data:ImRUHpeunifjLvp2QpSsXTWcdYoE3IgxYZoo/ILXmbC2FlhMLlDGhM1SYcRwfT4=,iv:NFB+IYkr/Qen6WJy/fCQ95UNGrAsaoce2rJkTNq6K0w=,tag:tI2CJnkwK3Sqg+aISbPrMQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y0kzuf0tn94a74whazwae4r9qal4snuqfuhl5jacscrpr7up5gts74fe5w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjTmJSbVFDRFVlYXgrcGtj
            SVd2R1loZHFFNU0zQ3p2enhQMGFJUHBYNDEwCmh3Q042VjEwaXJPQnh0OFBkN2k5
            a28ray83WlpFVW9EbnVrUS9jQTVUNDAKLS0tIDhvMG1zY2RDbDBKcWg3UEJqWmNo
            d2VzZ0NPVndlYUl4dytJVVQwSzNXb3MKZXyaD5AetUFdHxxpStEdnUXynj2ZqZwU
            zsqiP62R1ZHXZDcHHkz5JKmxz2RFBJePthm/ULP6kwoHNF2NfrdSOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-16T15:43:24Z"
    mac: ENC[AES256_GCM,data:13ntJQEDJ7jZdOpU/1VYxzhMNuJrzivjrqvg6AjB5IG8VtUsHDOHQX1aJUGbOZpplK6XLyK66k70RINOxdR0v6MMwFMTgHZZmEk5hoo6d6yu8R0CLRAE4+PnxISbPdiWNDUUB2cG2h5Qm9DCx/2EoB5GfS7Bfa2n8umxcI4QeMo=,iv:jFe0lCPeJKjQIpyQeTFnTxiEZbsyuYWhL4/EDXWbAh0=,tag:NcSPyioZvK+WxF9nQJ9xzw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
